version: 0.2
#웹훅 테스트...
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean
      - ./gradlew test --no-daemon
      - ./gradlew build --no-daemon --stacktrace

artifacts:
  files:
    - build/libs/*.jar
