version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin <account-id>.dkr.ecr.<region>.amazonaws.com

  build:
    commands:
      - ./gradlew clean
      - ./gradlew test
      - ./gradlew build --no-daemon
      - docker build -t $ECR_URI:latest  .

  post_build:
    commands:
      - docker push $ECR_URI:latest

artifacts:
  files:
    - '**/*'
