version: 0.2

env:
  secrets-manager:
    DOCKER_USER_NAME: "cj/dev/forever/cicdtest-aZvAJy:DOCKER_USER_NAME"
    DOCKER_PASSWORD: "cj/dev/forever/cicdtest-aZvAJy:DOCKER_PASSWORD"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "롼경 변수 테스트 $DOCKER_USER_NAME"
      - echo "Docker Credential 로드 완료"
      - echo "현재 브랜치: ${CODEBUILD_SOURCE_VERSION##*/}"
      - |
        BRANCH="${CODEBUILD_SOURCE_VERSION##*/}"
        case "$BRANCH" in
          main|develop) echo "$BRANCH 브랜치 빌드 시작" ;;
          *) echo "ERROR: 허용되지 않은 브랜치"; exit 1 ;;
        esac
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean
      - ./gradlew test --no-daemon
      - ./gradlew build --no-daemon --stacktrace

artifacts:
  files:
    - build/libs/*.jar
