version: 0.2

env:
  secrets-manager:
    DOCKER_USER_NAME: "cj/dev/forever/cicdtest-aZvAJy:DOCKER_USER_NAME"
    DOCKER_PASSWORD: "cj/dev/forever/cicdtest-aZvAJy:DOCKER_PASSWORD"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean
      - ./gradlew test --no-daemon
      - ./gradlew build --no-daemon --stacktrace

artifacts:
  files:
    - build/libs/*.jar
