version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Username: $DOCKER_USER_NAME"
      - echo "Password: $DOCKER_PASSWORD"
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean
      - ./gradlew test --no-daemon
      - ./gradlew build --no-daemon --stacktrace

artifacts:
  files:
    - build/libs/*.jar
