version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  
    commands:
      - echo "현재 브랜치: $CODEBUILD_SOURCE_VERSION"
      - |
        if [[ "$CODEBUILD_SOURCE_VERSION" == "refs/heads/main" ]]; then
          echo "main 브랜치에 대한 빌드를 시작합니다."
        elif [[ "$CODEBUILD_SOURCE_VERSION" == "refs/heads/develop" ]]; then
          echo "develop 브랜치에 대한 빌드를 시작합니다."
        else
          echo "main,develop 브랜치가 아닙니다."
          exit 1  
        fi
      - chmod +x ./gradlew 

  build:
    commands:
      - ./gradlew clean  
      - echo "🧪 테스트 코드 실행"
      - ./gradlew test  
      - echo "빌드 및 패키징 실행"
      - ./gradlew build --no-daemon  

artifacts:
  files:
    - build/libs/*.jar
