version: 0.2
phases:
  pre_build:
    commands:
      aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $ECR_REPOSITORY


  build:
    commands:
      - ./gradlew clean
      - ./gradlew test
      - ./gradlew build --no-daemon
      - docker build -t $ECR_URI:latest  .

  post_build:
    commands:
      - docker push $ECR_URI:latest

artifacts:
  files:
    - '**/*'
