version: '3.8'
services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - app-tier
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - app-tier

volumes:
  mysql-data:
    driver: local

networks:
  app-tier:
    driver: bridge


