spring:
  datasource:
    url: jdbc:mysql://forever-mysql-db.ctouy8o0uopm.ap-northeast-2.rds.amazonaws.com:3306/test
    username: ${AURORA_USERNAME}
    password: ${AURORA_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    region:
      static: ap-northeast-2  # 한국 리전
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

aws:
  sqs:
    queue-url: ""
